services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./zoo-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
    depends_on:
      - db
    volumes:
      - ./zoo-backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./zoo-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./zoo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
