/**
 * Zoo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateEnclosDto { 
    /**
     * Name of the enclosure
     */
    name: string;
    /**
     * Capacity of the enclosure
     */
    capacity: number;
    /**
     * Type of the enclosure (e.g., savane, aquatique)
     */
    type: string;
}

