/**
 * Zoo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnimalDto } from './animalDto';


export interface EnclosDto { 
    /**
     * Unique identifier of the enclosure
     */
    id: number;
    /**
     * Name of the enclosure
     */
    name: string;
    /**
     * Capacity of the enclosure
     */
    capacity: number;
    /**
     * Type of the enclosure (e.g., savane, aquatique)
     */
    type: string;
    /**
     * List of animals in the enclosure
     */
    animaux: Array<AnimalDto>;
}

